 platform :ios, '8.0'

target 'PimShare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PimShare

  #Object C
  pod 'CYLTabBarController', '~> 1.14.2'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'SAMKeychain', '~> 1.5.3'
#  pod 'MLeaksFinder', '~> 1.0.0'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'YYKit', '~> 1.0.9'
  pod 'FMDB', '~> 2.7.2'
  pod 'ZYCornerRadius', '~> 1.0.2'
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'TZImagePickerController', '~> 1.9.8'
  pod 'ACEDrawingView', '~> 2.2.1'
  pod 'FDFullscreenPopGesture', '~> 1.1'
  pod 'IQKeyboardManager', '~> 5.0.8'
  pod 'XLPhotoBrowser+CoderXL', '~> 1.2.0'
  pod 'CocoaLumberjack', '~> 3.4.1'

#Swift
pod 'GDPerformanceView-Swift', '~> 1.2.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'Alamofire', '~> 4.4.0'
pod 'SnapKit', '~> 4.0.0'
pod 'Kingfisher', '~> 4.1.1'
pod 'SwiftyJSON', '~> 4.0.0'
pod 'swiftScan', '~> 1.1.3'

pod 'RxSwift', '~> 4.1.2'
pod 'RxCocoa', '~> 4.1.2'
pod 'RxDataSources', '~> 3.0.2'
pod 'Differentiator', '~> 3.0.2'
pod 'ObjectMapper', '~> 3.1.0'
pod 'Then', '~> 2.3.0'

end
